version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: copy-webpack-plugin
    versions:
    - ">= 6.a, < 7"
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
    - 8.0.0
    - 8.1.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
